name: Build Raylib Example

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board to build for (all or specific board name)'
        required: true
        default: 'all'
      prefix:
        description: 'Prefix for binary name'
        required: true
        default: 'hello'
      flash_size:
        description: 'Size of the Flash storage'
        required: true
        default: '4MB'
      use_upstream_raylib:
        description: 'Update raylib submodule to the latest upstream main branch'
        required: false
        default: 'false'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp-box-3, m5stack_core_s3, esp32_p4_function_ev_board]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Target for ESP-IDF
        run: |
          echo "TARGET=$(case ${{ matrix.board }} in
            esp-box-3) echo 'esp32s3';;
            esp-box) echo 'esp32s3';;
            m5stack_core_s3) echo 'esp32s3';;
            esp32_p4_function_ev_board) echo 'esp32p4';;
            esp32_c3_lcdkit) echo 'esp32c3';;
            esp32_c6_devkit) echo 'esp32c6';;
            *) echo 'Unknown target'; exit 1;;
          esac)" >> $GITHUB_ENV

      - name: Update Raylib to Upstream Main (Optional)
        if: ${{ github.event.inputs.use_upstream_raylib == 'true' }}
        run: |
          git submodule update --init raylib/raylib
          cd raylib/raylib
          git fetch origin main
          git checkout main
          git pull origin main
          cd -

      - name: esp-idf build and merge binaries
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v6.0
          target: ${{ env.TARGET }}
          path: '.'
          command: |
            cd raylib/examples/hello
            idf.py @boards/${{ matrix.board }}.cfg build &&
            cd build.${{ matrix.board }} &&
            esptool.py --chip ${{ env.TARGET }} merge_bin -o ${{ github.event.inputs.prefix || 'hello' }}-${{ matrix.board }}.bin "@flash_args"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.prefix || 'hello' }}-${{ matrix.board }}.bin
          path: raylib/examples/hello/build.${{ matrix.board }}/${{ github.event.inputs.prefix || 'hello' }}-${{ matrix.board }}.bin
